### ISSUE TITLE
Using `venv-workon` or any tool that changes current python venv makes wakatime unusable.

### ISSUE THREAD

**Issue by CestDiego** [wakatime/wakatime-mode#7] opened 2015-06-03 04:36 UTC
This is because default wakatime-python-bin is `python`. Should support absolute path to the virtualenv wakatime is installed on, or otherwise provide instructions in setting this variable for yourself if you use venv-workon or sth like that.

**Comment by CestDiego** [comment] 2015-06-03 04:53
This can be fixed by specifying the `wakatime-python-bin` explicitly like so:

**Comment by alanhamlett** [comment] 2017-04-11 02:25
Duplicate of #16.

**Closed by alanhamlett** 2017-04-11 02:25 UTC
