### ISSUE TITLE
Debugger entered--Lisp error: (error "WakaTime Error (1)")

### ISSUE THREAD

**Issue by ChillarAnand** [wakatime/wakatime-mode#6] opened 2015-05-15 10:51 UTC
when i enable it throws error

```
Debugger entered--Lisp error: (error "WakaTime Error (1)")
  signal(error ("WakaTime Error (1)"))
  error("WakaTime Error (%s)" 1)
  #[(process signal) "\302!\303>\205%\304\305!!\210\306!\211\307U?\205$   \310U?\205$\311\312    \")\207" [process exit-status process-status (exit signal) kill-buffer process-buffer process-exit-status 0 102 error "WakaTime Error (%s)"] 4](#<process Shell> "exited abnormally with code 1\n")
```

**Comment by kevincolyar** [comment] 2015-06-01 21:07
Getting the same error when using with Spacemacs (https://github.com/syl20bnr/spacemacs)

**Comment by alanhamlett** [comment] 2015-06-01 22:38
This happens because wakatime-mode is loaded before the custom variables. Should be fixed with 82b134a64ec96df628c3ba35508166c117826e9a.

Try updating wakatime-mode to the latest version and let me know if it's fixed.

**Comment by kevincolyar** [comment] 2015-06-01 23:22
Still getting the error here.

**Comment by alanhamlett** [comment] 2015-06-01 23:23
Can you edit `wakatime-mode.el` and change the `"1 sec"` to `"3 sec"`, then restart emacs?

**Comment by kevincolyar** [comment] 2015-06-01 23:28
Still no luck

**Comment by kevincolyar** [comment] 2015-06-01 23:28
btw, i get the error when i try to edit or save

**Comment by alanhamlett** [comment] 2015-06-01 23:30
That's usually because the path to wakatime cli is incorrect. Can you paste your full error message from the `*Messages*` buffer?

**Comment by kevincolyar** [comment] 2015-06-01 23:34
```
error in process sentinel: WakaTime Error (1) [2 times]
```

I am using terminal emacs if that matters.

**Comment by alanhamlett** [comment] 2015-06-01 23:39
Terminal vs GUI shouldn't matter. Error code 1 means either Python or wakatime cli were not found. It's probably the path to wakatime cli. Can you make sure `wakatime-cli-path` in your `init.el` file is pointing to the same location that you get from running `which wakatime`?

**Comment by kevincolyar** [comment] 2015-06-01 23:47
Yep, it's there

```
/usr/local/bin/wakatime
```

Using homebrew.

**Comment by kevincolyar** [comment] 2015-06-01 23:56
Figured it out, needed:
```lisp
(setq wakatime-python-bin "/path/to/python")
```

**Comment by alanhamlett** [comment] 2015-06-02 00:04
Awesome!

**Comment by CestDiego** [comment] 2015-06-03 04:20
@kevincolyar awesome it worked! :D

**Comment by alanhamlett** [comment] 2015-06-03 04:51
Let's leave this open until I can fix it, since the plugin should prompt for the correct path if not found.

**Comment by CestDiego** [comment] 2015-06-03 04:52
I already opened another issue with more specific info: #7

**Comment by drewwells** [comment] 2015-06-05 16:47
I'm getting the same error and setting wakatime-python-bin didn't resolve it (python is already in my path). Also, everytime I save my file my entire screen flashes white. Goes away when I uninstall wakatime-mode. I'm using emacs prelude, so these settings are custom variables in `~/.emacs.d/personal/custom.el`. 

Wakatime-mode 20150601.1536 from melpa

**Comment by CestDiego** [comment] 2015-06-05 17:56
it has to be the full path  to python, not just "python"

**Comment by drewwells** [comment] 2015-06-05 18:19
The docs say as long as python is in the path, it should work. I also set it to "/usr/bin/python" but continued to get errors.

**Comment by lukaslozovski** [comment] 2015-06-25 15:47
+1

**Comment by victorsolis** [comment] 2015-07-21 21:24
Same issue here. Setting `wakatime-python-bin` didn't fix it.

**Comment by victorsolis** [comment] 2015-07-22 17:49
It works now. Fixed it by reinstalling wakatime.

**Comment by HenrikBengtsson** [comment] 2015-08-04 12:21
First time WakaTime user here: I got the same error message when trying to use this with GNU Emacs 24.3.1 on Windows.  The solution was to point `wakatime-cli-path` to the Python script `wakatime-script.py` and not the `wakatime.exe` binary (which you would get if you typed `which wakatime`). This is what my working Emacs settings are:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(global-wakatime-mode t)
 '(inhibit-startup-screen t)
 '(require-final-newline nil)
 '(wakatime-api-key "<my secret API key>")
 '(wakatime-cli-path "c:/Python27/Scripts/wakatime-script.py")
 '(wakatime-python-bin "c:/Python27/python.exe"))
```

(I'm not sure all of those settings are for WakaTime, but I included them just in case)

I've confirmed that https://wakatime.com/dashboard is now login my time.

**Comment by TheLoverZ** [comment] 2015-09-19 09:55
I've tried setting `wakatime-python-bin` but it didn't work, at that time I've noticed that pip version in 6.1.2(6.1.4?) so I updated it to 7.1.2(which is the latest), and uninstall & install wakatime again, then it worked :)

**Comment by son1112** [comment] 2016-03-17 01:14
I get the same errror when i lose a network connection. Closing all emacs clients and starting over fixes it, but that's a pain. Is there a way to "reset" wakatime?

**Comment by johnhamelink** [comment] 2016-08-25 07:39
If you're running a linux distribution where python 3 is the default python, be sure to set `wakatime-python-bin` to your python 2 binary. In Arch Linux, that means:

```lisp
'(wakatime-python-bin "/usr/bin/python2")
```

**Comment by ryukinix** [comment] 2016-09-21 22:52
Thanks, on ArchLinux set the custom variable as `'(wakatime-python-bin "/usr/bin/python2")` finally works the plugin!

**Comment by ryukinix** [comment] 2016-09-21 22:53
Would be better if this is not necessary... somebody here have plans to fix that? :heart:

**Comment by wdy1184** [comment] 2016-11-28 09:05
@drewwells Do you figure it out?

**Comment by drewwells** [comment] 2016-11-28 12:35
@wdy1184 I didn't, I lost interest in integrating it

**Comment by wdy1184** [comment] 2016-12-06 16:02
@drewwells I reinstall it, and it works well.

**Closed** 2017-04-11 02:21 UTC
